### PR TITLE
Depend on quickcheck-classes-base rather than vendoring quickcheck-classes

### PR DESCRIPTION
**Pull request by andrewthad**
This removes 3500 lines of vendored code from the test suite. I'll clean this up a little more later, but I wanted to make sure CI didn't find anything weird on older GHCs.

### CODE REVIEW

**Comment by cartazio** [comment]
Thx! Certainly long overdue ;)

**Comment by cartazio** [comment]
you are an ANGEL.
(i was a tad burnt out over the fall, so this todo languished too long, thanks for stepping up!)

**Comment by cartazio** [comment]
hrm, the law i had commented out were the ones I had trouble getting to type check when i did the nuclear vendoring,

**Comment by cartazio** [comment]
eh, i'll do that cleanup step myself i guess, in a day or so, thx for getting the ball rolling though

**Comment by andrewthad** [comment]
This passes all tests. It is ready to be squashed and merged.

**Comment by cartazio** [comment]
Awesome.  Thank you very much. I’m slowly surfacing but sounds good to me!

I’ll aim to look Tomorrow.  Need to get some good rest first ! :)

**Pull request merged**
