### PR TITLE
add Eq instances for MutableByteArray and MutablePrimArray

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This probably deserves a mention in the changelog, but other than that, LGTM.

**Comment by andrewthad** [comment]
Done.

**Comment by cartazio** [comment]
@RyanGlScott @andrewthad  .... i'd like to point out that Eq is usually not Reference/Ptr equality, its "same contents" equality ... are we sure we want to do that?

**Comment by RyanGlScott** [comment]
For a mutable data structure like `MutableByteArray`, I think pointer equality makes sense for its `Eq` instance, especially since that is a convention that other mutable data types like `IORef`, `STRef`, and `MVar` adhere to in their `Eq` instances.

**Comment by andrewthad** [comment]
As Ryan points out, this is already done pervasively throughout base.  Also, it’s the only possible instance.

**Comment by cartazio** [comment]
ok, you're both correct, but spelling it out helps a lot! (for me when i'm
slow, and for being able to circle back later :) )

**Comment by andrewthad** [comment]
I’ll add some documentation to the instance haddocks as well.  It can’t hurt to clarify there.

**Pull request merged**
