### PR TITLE
rename unsafe traversals

### PR DESCRIPTION
**Pull request by andrewthad**
Resolves https://github.com/haskell/primitive/issues/134

### CODE REVIEW

**Comment by treeowl** [comment]
CI fails. It looks like you missed a spot. Use git grep.

**Comment by cartazio** [comment]
The comments all mention the term affine but don’t explain it anywhere.  Recall that I myself was confused by your use of affine until I realized you meant it in the linear logical sense

**Comment by andrewthad** [comment]
Good point. I'll amend that in another PR.

**Comment by cartazio** [comment]
Great!

Could you also clarify the listt remark?  Eg backtracking / nondeterminism
monads such as ListT or LogicT?

Though this per se is possibly true for almost any code written on top of
prim monad.  Though I agree this sorta code is a likely culprit

**Pull request merged**
