### PR TITLE
remove PrimUnlifted instance for StablePtr

### PR DESCRIPTION
**Pull request by andrewthad**
Resolves https://github.com/haskell/primitive/issues/195

### CODE REVIEW

**Comment by treeowl** [comment]
I think it would be a good idea to add a note explaining why we don't have the instance, to (hopefully) prevent someone from trying to put it back.

**Comment by hvr** [comment]
stating the obvious: don't forget to major bump to 0.7.0

**Comment by treeowl** [comment]
@hvr, I think I disagree. Yes, removing an instance should trigger a major version bump, in theory. However, in this case, any version of any package that actually relies on this instance should be considered badly broken, as it will lead to segfaults. Such packages should get minor (bugfix) releases and their broken versions should be deprecated. Isn't it better to fail to compile than to compile to segfaulting code?

**Comment by andrewthad** [comment]
I've added a note to the changelog and to the module about the removed instance. I'm punting on the question of a major version for now, but my preference would be for this not to be a major version bump.

**Comment by andrewthad** [comment]
Spurious travis failure on GHC 8.0.2.

**Comment by hvr** [comment]
@treeowl you'd be conflating concerns if you do that; you'd be abusing the versioning policy to intentionally trigger compile failures; which in turn will force Hackage Trustees to go around and fix the upper bounds to `< 0.6.5` for the packages affected to rectify the metadata and make the packages compile again; iow, we're going to have to spend additional effort to work against your intentional compile failure sabotage act... ;-) and the end-result will be basically the same as if you'd hadn't deliberately violated the PVP to begin with; except that you've costed us more effort.

**Comment by hvr** [comment]
@treeowl instead, I'd suggest a different course of action which is more principled: 

- blacklist `primitive-0.6.4` so that the solver cannot access it anymore
- release `primitive-0.6.4.1` whose only change relative to the redacted `primitive-0.6.4` is that it removes the instance

Hackage trustees will still have to go around fixing up affected packages who started depending on that instance; but the big difference is that packages won't be able anymore to use `primitive-0.6.4` as it's not accessible to the solver anymore *at all*.

**Comment by cartazio** [comment]
If we’re removing a type class instance it’s a major versionbump.

**Comment by treeowl** [comment]
@hvr the principled course of action you propose is exactly what I was talking about. There's no major version bump there!

**Pull request merged**
