### PR TITLE
add functions for working with pinned PrimArrays

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by cartazio** [comment]
looks good, ithink i'm doing a 0.6.5 release later thi week, i'll make sure this is in my merge list

**Comment by cartazio** [comment]
this isn't gonna go into the bug fixe i've got planned, but hell yess gonna include it in the next feature release

**Comment by cartazio** [comment]
nice work so far!

**Comment by cartazio** [comment]
i'd like to add this to a 0.7.1 soon

**Comment by andrewthad** [comment]
Is anything preventing this from being merged?

**Comment by cartazio** [comment]
not  really :) 
add it in and add a post v0.7 entry to the change log and we can get started :)

**Pull request merged**
