### PR TITLE
Add instances for lazy ST

### PR DESCRIPTION
**Pull request by Avi-D-coder**
fix: #24

Code is @treeowl's from https://github.com/haskell/primitive/issues/24#issuecomment-276155819

### CODE REVIEW

**Comment by chessai** [comment]
Could you add `@since` pragmas?

**Comment by Avi-D-coder** [comment]
What would it take to get this merged?

**Comment by andrewthad** [comment]
I’m fine with this change. The change log entry is incorrect, but other than that, this looks fine.

**Comment by cartazio** [comment]
i'll take a look! was in a brain chemistry slow phase past month or three,
back in the grooove thing :)

**Comment by Avi-D-coder** [comment]
@andrewthad Fixed changelog

**Comment by cartazio** [comment]
sooo, i hate to be the bearer of bad news, but I think this shouldn't have been merged in at present.

until we no longer support GHC older than 8.2, cf https://gitlab.haskell.org/ghc/ghc/commit/2f5cb3d44d05e581b75a47fec222577dfa7a533e (and ticket https://gitlab.haskell.org/ghc/ghc/issues/13615), any code with the lazy st monad is WILDLY thread/concurrency *unsafe*

**Comment by Avi-D-coder** [comment]
Oh well

**Pull request merged**
