### PR TITLE
Test GHC 7.10 in CI

### PR DESCRIPTION
**Pull request by konsumlamm**

### CODE REVIEW

**Comment by konsumlamm** [comment]
It seems the issue was fixed in https://github.com/haskell/actions/pull/83, so I'll try again.

**Comment by konsumlamm** [comment]
The test suite passes now (the CI failure is caused by a timeout).

**Comment by konsumlamm** [comment]
@andrewthad could you please take another look?

**Comment by konsumlamm** [comment]
@andrewthad ping

The CI problem seems to be the same as in https://github.com/haskell/primitive/pull/326#issuecomment-1000393728.

**Comment by andrewthad** [comment]
This is just a guess, but try changing this:

```
    - name: Build
      run: cabal build
```

to this:

```
    - name: Build
      run: cabal build --enable-tests
```

**Comment by konsumlamm** [comment]
@andrewthad that doesn't change anything, although it shows that the problem is not with building the tests suite (see https://github.com/haskell/primitive/runs/4622761485).

Using `cabal configure --enable-tests` seems to work (although for some reason the last task can't find any runner).

I've marked this PR as a draft, because the CI currently fails for GHC 7.10 (see #329). Once that is merged, I'll readd 7.10 and while we're at it, we can also add 9.2 (although technically it's already tested, since `latest` is 9.2.1 currently).

**Comment by andrewthad** [comment]
Closing since GHC 7.10 will no longer be supported.

**Pull request closed without merging**
