### PR TITLE
add functions related to resizing mutable byte arrays

### PR DESCRIPTION
**Pull request by andrewthad**
Resolves https://github.com/haskell/primitive/issues/54 and https://github.com/haskell/primitive/issues/55

### CODE REVIEW

**Comment by andrewthad** [comment]
oh, I didn't realize that some of the size-related stuff didn't exist prior to GHC 8.0.

**Comment by schernichkin** [comment]
No updates since Apr 17 is it still actual? I need this function too.

**Comment by andrewthad** [comment]
I believe this will be resolved once [this PR](https://github.com/haskell/primitive/pull/64) is merged.

**Comment by andrewthad** [comment]
This has been handled elsewhere. Closing.

**Pull request closed without merging**
