### PR TITLE
add PrimUnlifted instances for TVar and MVar

### PR DESCRIPTION
**Pull request by andrewthad**
Resolves https://github.com/haskell/primitive/issues/75

### CODE REVIEW

**Comment by cartazio** [comment]
This sound non controversial.  I’ll check it this afternoon

**Comment by RyanGlScott** [comment]
This looks sensible to me.

I wonder: is there a comprehensive list of primitive types somewhere that have return kinds of `TYPE UnliftedRep`? It's possible that we've overlooked others, but this patch certainly seems fine in isolation.

**Comment by RyanGlScott** [comment]
I think I answered my own question: to find all such `TYPE UnliftedRep`-returning types, you'd need to search http://git.haskell.org/ghc.git/blob/5ab8094e4579c08973260c2d18599be0738526ec:/compiler/prelude/TysPrim.hs#l204 and find all uses of `UnliftedRep` (since they're primitive types, their types are all hard-wired directly into the compiler).

Again, I'm not suggesting you do this in this pull request, but it might be worth a separate audit.

**Comment by andrewthad** [comment]
@RyanGlScott Thanks. I went through that file and picked out three more: `Weak`, `ThreadId`, and `StablePtr`. I'm intentionally going to leave out `BCO#` because it's new and I don't know if it's expected to change any. Also, `Compact#` has to be left out because the the data constructor that wraps it takes several other fields. Sadly, `StableName#` must be omitted because nothing in `base` exports the data constructor of `StableName`.

**Comment by RyanGlScott** [comment]
Awesome! Thanks for being thorough, @andrewthad.

@cartazio, does this patch look good to you?

**Comment by treeowl** [comment]
Ryan, PrimUnlifted has convinced me that you were right: GHC should forbid
hand-written Generic instances. That would allow PrimUnlifted to have
generic default definitions for its methods. As it is, it can't, because
that would be unsafe. I think you should write a GHC proposal for that, or
I can.

**Comment by RyanGlScott** [comment]
Silly question: is there a particular hand-written `Generic` instance you had in mind when writing that comment? (I certainly can believe that you could end up with shenanigans, but the exact nature of the shenanigans is unclear to me.)

If you're feeling up to writing a proposal, I'd definitely support it :)

**Comment by treeowl** [comment]
Oh, wait a minute... I may have been wrong about that, now that I think of
it! Maybe it *can* be done safely. Let me give it a go. That won't help any
for the standard types that don't have Generic instances, but may help for
hand-written ones.

**Comment by treeowl** [comment]
Ryan, do you know why we can derive Generic for types with constructors
containing Addr# but not ones containing, e.g., Array#? This seems a bit
weird!

**Comment by RyanGlScott** [comment]
It's a long story. A good place to start is https://ghc.haskell.org/trac/ghc/ticket/10868.

Several stock classes, such as `Eq`, `Ord`, and `Show`, can be derived for data types with fields of certain unboxed types. These are generally of one the following six types:

* `Addr#`
* `Char#`
* `Double#`
* `Int#`
* `Float#`
* `Word#`

Because deriving `Generic` wasn't able to deal with these, we added the `URec` data family for `GHC.Generics`, and gave it six corresponding data family instances for each unboxed type.

Thus, deriving `Generic` can only handle those six particular primitive types at the moment since, well, that's all we gave it the power to do so. `URec` was made a data family so that in the future, we could extend it with the ability to work over more unboxed types if the situation called for it. (So we could conceivably add a case for `Array#`.)

That being said, I've never been super-happy with the current design. Perhaps it could be cleaned up now that we have levity polymorphism...

**Pull request merged**
