### PR TITLE
Remove Lazy ST instance on GHC >= 8.2

### PR DESCRIPTION
**Pull request by Avi-D-coder**
closes: #262

### CODE REVIEW

**Comment by Avi-D-coder** [comment]
@cartazio How is does this look right?

**Comment by Avi-D-coder** [comment]
@cartazio does this look right?

**Comment by cartazio** [comment]
Yeah, I’ll apply it on top of some patches I have locally.

**Comment by cartazio** [comment]
Also I like to do patches ff-only and sometimes I have a stack of patches
locally I want to apply :)

**Comment by cartazio** [comment]
merged in (essentially the same as this patch, but with a URI link about the commit in question)

**Comment by cartazio** [comment]
@Avi-D-coder  i'll add an attribution to you as "Avi Dessauer" for the change log, is that the correct name to use?

**Comment by Avi-D-coder** [comment]
@cartazio  Yep

**Pull request closed without merging**
