### PR TITLE
Support GHC 9.4

### PR DESCRIPTION
**Pull request by Bodigrim**
See https://gitlab.haskell.org/ghc/ghc/-/commit/20956e5784fe43781d156dd7ab02f0bff4ab41fb and  https://gitlab.haskell.org/ghc/ghc/-/commit/3570eda512d157a38da391b6f1d57dfbab72dd09

Cf. https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/primitive-0.7.3.0.patch

### CODE REVIEW

**Comment by chessai** [comment]
9.4 job got stuck, restarting it

**Comment by chessai** [comment]
On mobile and can't restart it for some reason, just cancel. Can someone (maybe @andrewthad or @Bodigrim) restart it?

**Comment by andrewthad** [comment]
GH litters the diff with CI warnings. Is the actual change just that one line telling newer versions of GHC to use the Word64# and Int64# types?

**Comment by Bodigrim** [comment]
@andrewthad correct, it's one-line change.

**Pull request merged**
