### PR TITLE
add since metadata from 0.6 to 0.6.3

### PR DESCRIPTION
**Pull request by chessai**
@andrewthad added `since` metadata for everything coming up in 0.6.4.0, this PR adds stuff for 0.6.0.0 to 0.6.3.0

### CODE REVIEW

**Comment by andrewthad** [comment]
The annotations for `sizeOf` and `alignment` are a little misleading. These functions have [existed since `0.1`](http://hackage.haskell.org/package/primitive-0.1/docs/Data-Primitive.html), but they were defined in `Data.Primitive`, and then they got moved into `Data.Primitive.Types` in `0.6.3`. Perhaps it would be best to just explicitly state that in version of `primitive` prior to `0.6.3`, these function were only available through `Data.Primitive`.

**Comment by chessai** [comment]
@andrewthad I just pushed the discussed change

**Comment by andrewthad** [comment]
This looks good to me. I'll wait a day for anyone else to weigh in and then merge if there are no concerns voiced.

**Comment by andrewthad** [comment]
The build failure is just the result of an issue with `quickcheck-classes` that has since been fixed. Merging.

**Pull request merged**
