### PR TITLE
Add getSizeofSmallMutableArray

### PR DESCRIPTION
**Pull request by treeowl**

### CODE REVIEW

**Review by chessai — APPROVED** [review]

**Comment by treeowl** [comment]
@chessai I added some documentation since your review. Would you mind giving it a once-over?

**Comment by konsumlamm** [comment]
So `sizeofSmallMutableArray` sometimes returns the wrong result? We should think about deprecating it then, just like the underlying primitive.

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
Agree that it should be a separate issue. For now this LGTM.

**Comment by treeowl** [comment]
I've opened #373 to discuss that.

**Comment by treeowl** [comment]
Thanks for the review, @chessai .

**Pull request merged**
