### PR TITLE
ban vim swap files in .gitignore

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I'm generally of the opinion that these sorts of things should be placed in a global `.gitignore` file, as they're rather language-agnostic.

**Comment by chessai** [comment]
That makes sense. I think I mostly agree with that.

**Comment by andrewthad** [comment]
I agree with David. I don't mind having them here even though people should have these globally.

**Comment by chessai** [comment]
Can this just be merged then? There are no breaking changes presented, just 3 lines in a .gitignore

**Pull request merged**
