### PR TITLE
Version bump, document new additions in changelog.

### PR DESCRIPTION
**Pull request by dolio**

### CODE REVIEW

**Comment by hvr** [comment]
btw, it's not obvious from the changelog why a major version bump was performed (which deserves to be made apparent in a changelog, IMHO :-) )

**Comment by cartazio** [comment]
Probably the dropped support for 7.4?

**Comment by hvr** [comment]
@cartazio why would dropping support for GHC 7.4/base-4.5  require a major version bump? :-)

**Comment by dolio** [comment]
I could lower the version increment. I simply thought that adding two completely new modules plus dropping support for certain versions was a fairly significant change.

**Comment by hvr** [comment]
Well, the problem here is packages depending on `primitive` which rely on PVP contract. Those will have to go through the API review process (due to a major version increment being signalled) to decide whether it's safe to allow that new version of `primitive`.

However, adding a new module is merely an API addition (i.e. minor version bump), while constraining the version range of supported dependencies is totally benign (as it can't break the semantics or compilation of any existing API consumer) and would at best require a patch-level increment.

So from the point of view of the PVP, this is not a "significant change" at all, but merely a (significant) API  addition.

**Comment by cartazio** [comment]
Makes sense.

As long as it's easy to see this stuff via the change log I guess that's
all good

**Pull request merged**
