### PR TITLE
add Eq instances for MutableByteArray and MutablePrimArray

### PR DESCRIPTION
**Pull request by andrewthad**
Resolves https://github.com/haskell/primitive/issues/240

### CODE REVIEW

**Comment by andrewthad** [comment]
Build failure on GHC 8.8 is because of `MonadFail` problems with the `time` library, not because of anything in the PR.

**Comment by RyanGlScott** [comment]
The error reported in https://github.com/haskell/primitive/pull/241#issuecomment-495928260 is almost surely due to a stale `haskell-ci`-generated `.travis.yml` file. I originally set out to regenerate this, but I ran into #243, so I'm stopping until I can get a resolution on that issue.

**Comment by cartazio** [comment]
I regenerated the Travis files a few weeks ago, but I couldn’t figure out a fix for time.  How do we do that ?

**Comment by RyanGlScott** [comment]
This issue is caused by a [`haskell-ci` bug](https://github.com/haskell-CI/haskell-ci/issues/249) in the current Hackage release (0.2.1). This bug has been fixed in the current HEAD version of `haskell-ci`, so regenerating the file with `haskell-ci` HEAD should be sufficient.

**Comment by cartazio** [comment]
Oh ok.  I’ll regeneratw master from that.

**Comment by cartazio** [comment]
Or you can. Whatever makes sense

**Comment by RyanGlScott** [comment]
I've just pushed some commits to `master` which restore a working build. @andrewthad, rebasing this PR on top of `master` should fix your build issues.

**Comment by andrewthad** [comment]
I cannot force push, so I cannot pushed my rebased commit. Is there a reason that force push is disabled for branches other than master?

**Comment by cartazio** [comment]
Delete the branch name and push it again

**Comment by andrewthad** [comment]
Deleting the branch caused github to close this PR, but I've reopened it. It looks like travis is attempting to build this now.

**Comment by andrewthad** [comment]
I think we're still getting the same travis failure on GHC 8.8:

```
lib/Data/Time/Format/Parse.hs:111:12: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
```

**Comment by RyanGlScott** [comment]
The `eq_mutable_byte_array` branch still doesn't have the latest commits from `master`, so this doesn't surprise me. Did you mean to choose a different branch?

**Comment by RyanGlScott** [comment]
By the way, one alternative to force-pushing is to push separate commits and then use GitHub's Squash and merge (or Rebase and merge) features to actually land the patch.

The fact that you can't force-push is an artifact of `primitive` being in the `haskell` GitHub group, which appears to have some global configuration that prevents force-pushing. (Alas, I can't change this setting.)

**Comment by andrewthad** [comment]
You're right. I goofed that up. Although now that I've actually rebased on top of master, deleted the remote branch, and recreated the remote branch, github will not let me reopen the PR. The alt-text over the "Reopen and comment" button is:

> The eq_mutable_byte_array branch was force-pushed or recreated

Apparently, github is smart enough to know that disabling force-pushing should also disable recreating branches (which makes sense since you can otherwise thwart the guarantee it's trying to provide). Can someone change this setting?

**Comment by andrewthad** [comment]
Sorry, that comment was at the same time.

> By the way, one alternative to force-pushing is to push separate commits and then use GitHub's Squash and merge (or Rebase and merge) features to actually land the patch.

That's clever. I'm just going to give up on doing this cleanly though and just open a new PR.

**Comment by andrewthad** [comment]
Closing in favor of https://github.com/haskell/primitive/pull/246

**Pull request closed without merging**
