### PR TITLE
Resurrect benchmarks

### LINKED ISSUE #298: Benchmarks don't compile
It would be good to add building of benchmarks to the CI, so this situation could be avoided in the future. For now, however, the problem is that `UnliftedArray` has been removed, but the benchmark suite still depends on it:

```
primitive-benchmarks> [3 of 6] Compiling ByteArray.Compare
primitive-benchmarks>             
primitive-benchmarks> /home/lehins/haskell/primitive/bench/ByteArray/Compare.hs:22:14: error:
primitive-benchmarks>     Not in scope: type constructor or class ‘UnliftedArray’
primitive-benchmarks>    |        
primitive-benchmarks> 22 | benchmark :: UnliftedArray ByteArray -> Int
primitive-benchmarks>    |              ^^^^^^^^^^^^^
primitive-benchmarks>             
primitive-benchmarks> /home/lehins/haskell/primitive/bench/ByteArray/Compare.hs:59:18: error:
primitive-benchmarks>     Not in scope: type constructor or class ‘UnliftedArray’
primitive-benchmarks>    |        
primitive-benchmarks> 59 | argumentSmall :: UnliftedArray ByteArray
primitive-benchmarks>    |                  ^^^^^^^^^^^^^
primitive-benchmarks>             
primitive-benchmarks> /home/lehins/haskell/primitive/bench/ByteArray/Compare.hs:75:19: error:
primitive-benchmarks>     Not in scope: type constructor or class ‘UnliftedArray’
primitive-benchmarks>    |        
primitive-benchmarks> 75 | argumentMedium :: UnliftedArray ByteArray
primitive-benchmarks>    |                   ^^^^^^^^^^^^^
primitive-benchmarks>             
primitive-benchmarks> /home/lehins/haskell/primitive/bench/ByteArray/Compare.hs:87:18: error:
primitive-benchmarks>     Not in scope: type constructor or class ‘UnliftedArray’
primitive-benchmarks>    |        
primitive-benchmarks> 87 | argumentLarge :: UnliftedArray ByteArray
primitive-benchmarks>    |                  ^^^^^^^^^^^^^
primitive-benchmarks>  
```

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #298 and #313.

### CODE REVIEW

**Comment by chessai** [comment]
Can you update the repo's README as well? It will no longer be accurate when talking about benchmarks.

**Comment by Bodigrim** [comment]
@chessai done. I assume it's acceptable to remove additional instructions, since now both tests and benchmarks work in a standard way.

**Comment by chessai** [comment]
> @chessai done. I assume it's acceptable to remove additional instructions, since now both tests and benchmarks work in a standard way.

Right.

This can be merged once CI finishes.

**Comment by Bodigrim** [comment]
@chessai all green.

**Comment by chessai** [comment]
@Bodigrim thanks!

**Pull request merged**
