### PR TITLE
Allow building with base-4.14.*, ghc-prim-0.6.*

### PR DESCRIPTION
**Pull request by RyanGlScott**
GHC 8.10.1 comes bundled with `base-4.14.0.0` and `ghc-prim-0.6.1`, so this patch adjusts `primitive`'s upper version bounds to allow building with these versions. Judging from the respective changelog entries for [`base-4.14.*`](https://gitlab.haskell.org/ghc/ghc/blob/97d0b0a367e4c6a52a17c3299439ac7de129da24/libraries/base/changelog.md) and [`ghc-prim-0.6.*`](https://gitlab.haskell.org/ghc/ghc/blob/97d0b0a367e4c6a52a17c3299439ac7de129da24/libraries/ghc-prim/changelog.md), neither release impacts the code in `primitive`.

### CODE REVIEW

**Comment by cartazio** [comment]
I’ll poke at this later today or tomorrow. Though if a trustee bumps 0.7 on
hackage before I get to it please comment here :)

**Comment by asr** [comment]
I'm waiting a release including this PR (blocking https://github.com/agda/agda/issues/4242).

**Comment by cartazio** [comment]
Sooo!  I’ll do that later today.
Was a bit buried with getting vector out.

**Comment by cartazio** [comment]
@RyanGlScott plz confirm that the hackage revision is correct for you :)

**Comment by RyanGlScott** [comment]
Looks good to me. Thanks!

**Comment by asr** [comment]
@cartazio, sorry for the rough comment. Thank you for the Hackage revision.

**Comment by cartazio** [comment]
@asr that was a polite and reasonable comment In the continuum of messages / ticket exchanges maintainers of widely used tools get!  A little nudge that’s a reminder in the juggling act of life.  Reminders that just help keep things in the queue are super reasonable. 

I’m currently reevaluating what support range primitive and vector should support and if that’s the “worst” I get then things are going well. (But seriously : who is building new Haskell code that needs a ghc older than 8.2 for building the end application of new code?

**Comment by asr** [comment]
Agda (upstream) is currently tested with GHC 8.0.2, 8.2.2, 8.4.4, 8.6.5 and 8.8.2.

**Comment by cartazio** [comment]
cool, so "5 most recent major versions" policy?

**Comment by asr** [comment]
No officially :-) GHC is moving faster these days, you know.

**Pull request merged**
